FROM nginx:1.23.3

COPY index.html /usr/share/nginx/apcragg-space/
COPY static /usr/share/nginx/apcragg-space/static
COPY nginx.conf /etc/nginx/nginx.conf
COPY apcragg-space /etc/nginx/sites-enabled/
